### ISSUE TITLE
[Roadmap] Q2 2024

### ISSUE THREAD

**Issue by peterschmidt85** [dstackai/dstack#1116]
This issue outlines the major items planned for Q2 2024. Note that it doesn't include bug fixes, except for major issues. 

> [!WARNING]
> This roadmap is replaced by #1350.

### Core features
- [ ] **Implement `dstack apply`** #1223 #1326 #1327 #1571 #1472
- [ ] **Allow attaching volumes** #1158 #1467
- [x] **Multi-node support**  #1103 #1337
- [x] **Support for on-prem servers** #1115 #1189
- [x] **Support private subnets** #1201 #1171 #1264 #1304 
- [x] Allow instance reuse by other users #896
- [x] Make sure retry policy works for all types of instances #1200 
- [x] **More granular permissions** #1101  #1138 
- [x] **Parity YAML and CLI** #943 #1011  

### Architecture
- [ ] **AMD GPU** #1413
- [ ] **Intel Gaudi**
- [ ] **TPU** #956 #1337
- [ ] Intel GPU
- [ ] AWS Inferentia
- [ ] AWS Trainium

### New providers
- [x] **RunPod** #1063 #1137 #1118 #1297
- [x] **Oracle** #1194 

### Provider improvements
- [ ] **Reserved instances in AWS** #1155
- [ ] **H100 support in Azure** #1239
- [ ] Reserved instances in GCP
- [ ] Reserved instances in Azure
- [ ] AMD support in Azure
- [ ] AMD support in GCP
- [x] Spot instances in RunPod
- [x] Bare metal support in Oracle #1194
- [x] Multi-node support in Oracle #1194
- [ ] Spot instances in Oracle
- [ ] Spot instances in TensorDock
- [ ] Spot instances in Vast.ai
- [x] **A10 support in Azure** #1014
- [x] **H100 support in AWS** #1238
- [x] **H100 support in GCP** #1240
- [x] **L4 support in AWS** #1235

## Examples

> [!IMPORTANT]
> Community help is needed!

- [ ] **TensorRT-LLM**
- [ ] **Triton**
- [ ] **Function calling**
- [ ] LoRAX
- [x] **H4 Alignment Handbook** #1180
- [x] **Axolotl** #1187

## Documentation
- [ ] **Troubleshooting**
- [x] **Protips**

> [!IMPORTANT]
> If you notice something important missing here, please write about it in the comments.

**Comment by peterschmidt85** [comment]
Replaced by https://github.com/dstackai/dstack/issues/1350
