### ISSUE TITLE
[Roadmap] Q4 2024

### ISSUE THREAD

**Issue by peterschmidt85** [dstackai/dstack#1782]
This issue outlines the major items planned for Q4 2024.

For major bugs, see https://github.com/dstackai/dstack/labels/major

- **Gateway & Services**
   - [x] #1595 
   - [x] #1926
   - [x] #1762
   - [x] #1349 
   - [x] #1777
- **Observability**
  - [x] #1761
  - [ ] Service & LLM metrics
  - [x] #1763
 - **Distributed training**
   - [x] #1781
   - [x] #1804
   - [x] #1489
   - [x] #1337
   - [ ] Lambda 1CC
- **Volumes**
  - [x] #1863 
  - [x] #1481 
  - [x] #1949
  - [ ] #1467
- **On-prem**
  - [x] #1796
  - [ ] NFS on-prem volumes
  - [x] #1862
  - [x] #1381
- **UI**
  - [x] #1683
  - [x] #1639
  - [x] #1723 
- **Misc**
   - [x] #1926
   - [x] #1448
   - [x] #1535
   - [x] #708 
   - [x] #1838
   - [x] #1672
   - [x] #1155
   - [x] #1239
   - [ ] Support for H200 in AWS/GCP/Azure and other providers
- **Experimentation**
   - [x] #1631
   - [ ] Treat gateways as runs to cover these issues:
     - #1664
     - #1402
     - gateways support in various backends
     - #1673
   - [x] #1780
  - [ ] Intel Gaudi support
- **Examples**
  - [x] #1751
  - [x] #1623
  - [x] #1748
  - [x] #1787
  - [x] #1749
  - [ ] #1752
  - [x] #1753
  - [x] #1750
  - [ ] Whisper
  - [x] #1752
  - [ ] Ray
  - [ ] Spark

**Comment by peterschmidt85** [comment]
Closed. See #2184
